# Vim Mode!!!
bindkey -v
bindkey "\e[3~" delete-char

# editor
export EDITOR=nvim

# Starship
eval "$(starship init zsh)"

# Aliases
alias vim="nvim"
alias ls="exa"
alias lsa="exa --icons -la"
alias df="duf"
alias ps="procs"

# ENV
export PATH=$PATH:~/.local/bin:~/scripts

# History
export HISTFILE=${HOME}/.zsh_history
export HISTSIZE=1000
export SAVEHIST=100000
setopt hist_ignore_dups
setopt EXTENDED_HISTORY

# For extra completion
fpath+=${ZDOTDIR:-~}/.zsh_functions

# zinit
source ~/.myzinit

# zoxide
eval "$(zoxide init zsh)"

