keys:
  - &admin age1409zj4a4lzupezp4u099sdthkj3k03n0hqksmfll2ls70wgxxs5qkajumd
  - &asu age12l38h8007lakcjl8ztx20mxpy2tcn3wutc8h7jzfn3xuqxxrfvqqayuwaq
creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
    - age:
      - *admin
      - *asu
  - path_regex: profiles/[^/]+/secrets\.yaml$
    key_groups:
    - age:
      - *admin
      - *asu
