#!/usr/bin/env bash

if [ "$#" -ne 1 ]; then
    echo "Error: specify drive letter to mount."
    exit 1
fi

sudo mkdir -p /mnt/"$1"
sudo mount -t drvfs "$1": /mnt/"$1" -o uid=$(id -u),gid=$(id -g),fmask=113,dmask=022
