# Vim Mode!
bindkey -v

# Starship
eval "$(starship init zsh)"

alias ls="ls --color=auto"
alias vim="nvim"
export PATH="$PATH:/opt/riscv/bin:/opt/qemu-riscv/bin"
export PATH="$PATH:/home/nanami/.local/bin:/usr/local/go/bin:/home/nanami/.go/bin"
export GOPATH="/home/nanami/.go"
export PATH="$PATH:/home/nanami/scripts"

# History
export HISTFILE=${HOME}/.zsh_history
export HISTSIZE=1000
export SAVEHIST=100000
setopt hist_ignore_dups
setopt EXTENDED_HISTORY

# For extra completion
fpath+=${ZDOTDIR:-~}/.zsh_functions

# zinit
source ~/.myzinit

