eval $(/opt/homebrew/bin/brew shellenv)
export MANPATH=/opt/local/share/man:$MANPATH
path=(
    "/opt/local/bin:/opt/local/sbin"
    "/Users/nanami/Library/Application Support/JetBrains/Toolbox/scripts"
    "$path[@]"
)
