# Nanamiiiii's zshrc for mbp
# Last Update: 2023/8/11
# Load common configuration
source "$ZDOTDIR/zshrc.common"

# Additional Settings
path=(
    "/opt/homebrew/opt/curl/bin"(N-/)
    "/opt/homebrew/opt/python@3.11/libexec/bin"(N-/)
    "/opt/homebrew/opt/openjdk/bin"(N-/)
    "$path[@]"
)

# sudo prompt
export SUDO_PROMPT='[sudo] %p: '

