# Nanamiiiii's zshrc for mbp
# Last Update: 2023/8/11
# Load common configuration
source "$ZDOTDIR/zshrc.common"

# Additional Settings
path=(
    "/opt/homebrew/opt/curl/bin"(N-/)
    "/opt/homebrew/opt/python@3.11/libexec/bin"(N-/)
    "/opt/homebrew/opt/openjdk/bin"(N-/)
    "/Library/Frameworks/Python.framework/Versions/3.11/bin"
    "$path[@]"
)

# sudo prompt
export SUDO_PROMPT="[sudo] %p's password: "

# 1Password SSH Agent
SSH_AUTH_SOCK=~/Library/Group\ Containers/2BUA8C4S2C.com.1password/t/agent.sock

