# Vim Mode!!
bindkey -v

# Starship
eval "$(starship init zsh)"

# Personal Config
alias vim="nvim"
alias ls="ls --color=auto"
export PATH="$PATH:/home/nanami/scripts"
export GOPATH=~/.go
export PATH="$PATH:/usr/local/go/bin:$GOPATH/bin:$HOME/.local/bin:/opt/riscv/bin:/opt/riscv-openocd/bin"

# History
export HISTFILE=${HOME}/.zsh_history
export HISTSIZE=1000
export SAVEHIST=100000
setopt hist_ignore_dups
setopt EXTENDED_HISTORY

# For extra completion
fpath+=${ZDOTDIR:-~}/.zsh_functions

# zinit
source ~/.myzinit

