#!/bin/sh

XDG_SESSION_TYPE=wayland
XDG_CURRENT_DESKTOP=sway
XDG_CURRENT_SESSION=sway
DESKTOP_SESSION=sway
LIBSEAT_BACKEND=logind
QT_QPA_PLATFORM="wayland;xcb"
GDK_DPI_SCALE=1
QT_SCALE_FACTOR=1
QT_AUTO_SCREEN_SCALE_FACTOR=0
QT_QPA_PLATFORMTHEME=qt6ct
QT_IM_MODULE=fcitx
#MOZ_ENABLE_WAYLAND=1
_JAVA_AWT_WM_NONREPARENTING=1

export XDG_SESSION_TYPE XDG_CURRENT_DESKTOP XDG_CURRENT_SESSION DESKTOP_SESSION LIBSEAT_BACKEND QT_QPA_PLATFORM GDK_DPI_SCALE QT_SCALE_FACTOR QT_AUTO_SCREEN_SCALE_FACTOR QT_QPA_PLATFORMTHEME QT_IM_MODULE _JAVA_AWT_WM_NONREPARENTING;

systemd-cat --identifier=sway sway "$@"

