gPACESHIP_PROMPT_DEFAULT_PREFIX=""

SPACESHIP_PROMPT_ADD_NEWLINE=true
SPACESHIP_PROMPT_SEPARATE_LINE=true

SPACESHIP_PROMPT_ORDER=(
  user
  host
  os
  custom_dir
  nix_shell
  docker
  git
  rust
  package
  exit_code
  exec_time
  line_sep
  char
)

SPACESHIP_CDIR_TRUNC=2
SPACESHIP_CDIR_COLOR="4"
SPACESHIP_CDIR_PREFIX="%F{244}%bin %f"
SPACESHIP_CDIR_SUFFIX=" "
SPACESHIP_CDIR_LOCK_SYMBOL=" 󰌾 "

SPACESHIP_USER_SHOW="always"
SPACESHIP_USER_COLOR="12"

SPACESHIP_HOST_SHOW="true"
SPACESHIP_HOST_COLOR="8"
SPACESHIP_HOST_COLOR_SSH="8"
SPACESHIP_HOST_PREFIX="%F{8}@%f"

SPACESHIP_GIT_SYMBOL="󰘬 "
SPACESHIP_GIT_PREFIX=""
SPACESHIP_GIT_STATUS_UP_TO_DATE=" "
SPACESHIP_GIT_STATUS_UNTRACKED="󰝒 "
SPACESHIP_GIT_STATUS_MODIFIED="󱇧 "
SPACESHIP_GIT_STATUS_DELETED="󰮘 "
SPACESHIP_GIT_STATUS_STASHED=" "
SPACESHIP_GIT_STATUS_UNMERGED=" "
SPACESHIP_GIT_STATUS_AHEAD="⇡"
SPACESHIP_GIT_STATUS_BEHIND="⇣"
SPACESHIP_GIT_STATUS_DIVERGED="⇕"
SPACESHIP_GIT_STATUS_PREFIX=" "
SPACESHIP_GIT_STATUS_SUFFIX=""

SPACESHIP_PACKAGE_PREFIX=""

SPACESHIP_NIX_SHELL_SYMBOL=" "
SPACESHIP_NIX_SHELL_COLOR="4"

SPACESHIP_EXEC_TIME_SHOW=true
SPACESHIP_EXEC_TIME_COLOR="#e2e2e5"

SPACESHIP_EXIT_CODE_SHOW=true
SPACESHIP_EXIT_CODE_SYMBOL="✘ "

SPACESHIP_ASYNC_SHOW=false

SPACESHIP_CHAR_SYMBOL="❯ "

# SPACESHIP_TIME_SHOW=true

