# Vim Mode!!!
bindkey -v
bindkey "\e[3~" delete-char

# Starship
eval "$(starship init zsh)"

# Customize to your needs...
alias vim="nvim"
alias ls="ls --color=auto"
export GOBIN=~/.go/bin
export PATH=$PATH:$GOBIN:~/.local/bin:/var/lib/snapd/snap/bin
export PATH=$PATH:/opt/riscv/bin:/opt/riscv-musl-10/bin:/opt/riscv-qemu/bin
export KEYSTONE_SDK_DIR=/opt/keystone-sdk

# History
export HISTFILE=${HOME}/.zsh_history
export HISTSIZE=1000
export SAVEHIST=100000
setopt hist_ignore_dups
setopt EXTENDED_HISTORY

# For extra completion
fpath+=${ZDOTDIR:-~}/.zsh_functions

# zinit
source ~/.myzinit

