# Load common config
source "$ZDOTDIR/zshrc.common"

path=(
    "/var/lib/snapd/snap/bin"(N-/)
    "/home/linuxbrew/.linuxbrew/bin"(N-/)
    "$path[@]"
)

export SSH_AUTH_SOCK=~/.1password/agent.sock

