name: Build NixOS configurations on nixbuild.net

on:
  push:
    branches:
      - main
  workflow_dispatch: 

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nixos-build:
    name: Build NixOS configuration for ${{ matrix.profile }}
    runs-on: ubuntu-latest
    timeout-minutes: 180
    strategy:
      fail-fast: false
      matrix:
        profile:
          - nyan
          - nacho
          - yuki
          - mafu
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Install Nix
        uses: cachix/install-nix-action@v31
      - name: Configure nixbuild.net
        uses: nixbuild/nixbuild-action@v27
        with:
          nixbuild_token: ${{ secrets.NIXBUILD_TOKEN }}
          generate_summary_for: 'workflow'
          settings: |
            build-summary-log-format = logfmt
            caches = s3://nix-cache?region=auto&endpoint=https://212cd12a44cb9c8f000d70ea06dcb593.r2.cloudflarestorage.com&secret-key=${{ secrets.NIX_CACHE_SIGNING_KEY }}&addressing-style=path
            access-tokens = s3://nix-cache=${{ secrets.R2_ACCESS_KEY_ID }}:${{ secrets.R2_SECRET_ACCESS_KEY }}
      - name: Build
        run: |
          nix build \
            ".#nixosConfigurations.${{ matrix.profile }}.config.system.build.toplevel" \
            --accept-flake-config \
            --no-write-lock-file \
            --no-link \
            --print-build-logs \
            --show-trace \
            --builders "" \
            --max-jobs 2 \
            --eval-store auto \
            --store ssh-ng://eu.nixbuild.net
