name: Build Fedora based devenv image

on:
  push:
    branches:
      - "main"
    paths:
      - "nvim/*"
      - "vsnip/*"
      - "zsh/*"
      - "tmux/tmux.conf"
      - "starship/starship.toml"
      - "docker/Dockerfile.fedora"
      - ".github/workflows/docker-dev-fedora.yml"
      
  schedule:
    - cron: "0 0 */7 * *"
  
  workflow_dispatch: 
    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: nanami-devenv-fc
  
jobs:

  package:

    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log into registry ghcr.io
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/nanamiiiii/${{ env.IMAGE_NAME }}
        tags: |
          type=raw,value=latest
          type=raw,value={{date 'YYYYMMDD' tz='Asia/Tokyo'}}-{{sha}}
          
    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        file: docker/Dockerfile.fedora
        target: runner
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64,linux/arm64
